# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: sudo apt -y install azure-cli
    init: echo "this is the prebuild"
    command: echo 'start script'
