# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      az bicep install
      az bicep upgrade
    init: echo "this is the prebuild"
    command: echo 'start script'
